management.endpoints.web.exposure.include=refresh,health,info

# 1. How many traces to send (1.0 = 100% of requests. Use 0.1 in production)
management.tracing.sampling.probability=1.0

# 2. Where to send the traces
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# 3. Include IDs in the logs (Very important for debugging)
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]



