spring.application.name=user-service
server.port=8082
spring.jpa.hibernate.ddl-auto = update
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=jahns
spring.datasource.password=postgresql
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=INFO
jwt.secret=V2VyeVNlY3VyZVN0YXRpY0Jhc2U2NEVuY29kZWRLZXlGb3JGb29kabcd
contact.name=JahnaviSomashekar
contact.message = Hello from user service
